val reviews = sc.textFile("/FileStore/tables/2nvthuy01489287138693/textinput.txt")
val count = reviews.flatMap(line=> line.split(" "))
                    .map(word=>(word,1))
                    .reduceByKey(_+_)
                    .map(a=>a.swap)
                    .sortByKey(false,1)
                    .map(a=>a.swap)
                    .take(10)
                    .foreach(println)
